const EJERCICIOS_DISPONIBLES = [
  "Abdominales",
  "Aperturas con mancuernas",
  "Bíceps en polea",
  "Crunch en máquina",
  "Curl con barra",
  "Curl con mancuernas",
  "Curl de isquiotibiales",
  "Dominadas",
  "Elevaciones frontales",
  "Elevaciones laterales",
  "Extensiones de cadera",
  "Extensiones de tríceps",
  "Fondo en paralelas",
  "Jalón al pecho",
  "Leg Press (Prensa)",
  "Peso Muerto",
  "Peso Muerto Rumano",
  "Plancha",
  "Press Arnold",
  "Press de Banca",
  "Press de Banca Inclinado",
  "Press Francés",
  "Press Militar",
  "Remo con barra",
  "Remo en polea baja",
  "Sentadilla Búlgara",
  "Sentadilla Libre",
  "Sentadilla en Máquina Smith",
].sort();

export default EJERCICIOS_DISPONIBLES;
